### ISSUE TITLE
Some events don't have an action

### ISSUE THREAD

**Issue by datitisev** [YappyBots/YappyGitLab#31]
From #28:

![img](https://camo.githubusercontent.com/1e7bdc7d01c2207312d5c49650641f00783b6471/68747470733a2f2f692e696d6775722e636f6d2f686e35497537382e706e67)

**Comment by datitisev** [comment]
@noraj Can you look at the payload of the webhook and send it to me, here or through Discord? I cannot seem to reproduce this issue.

To look at the payload:
1) Settings -> Integrations
2) Click "Edit" button in webhook
3) Click more details for Issue request

**Comment by noraj** [comment]
@datitisev I sent you details on private message on discord.

**Comment by datitisev** [comment]
@noraj I've pushed a change that may fix it. If you could resend the hook that was causing the bug, that'd be great. To do so, just go to the details view of my previous comment, and click "Resend".

**Comment by noraj** [comment]
I have still the same problem. Tell me if you need mroe info.

**Comment by datitisev** [comment]
Root cause of this bug found. This occurs when you use the "Test" dropdown in the GitLab webhook edit page to test an event.
Instead of testing an actual event, for issues what it does is send the payload of a random issue.

**Comment by datitisev** [comment]
**Test Issue** styled

![image](https://user-images.githubusercontent.com/6401250/40626305-b40f4598-6285-11e8-98e9-bcac1ed56d0c.png)

**Comment by beonard6** [comment]
Testing merge_request has same issue
